name: Test

on:
  push:
    branches:
      - master

jobs:
  test_coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.8
      - name: Install Flit
        run: pip install flit
      - name: Install Dependencies
        run: make install
      - name: Test
        run: pytest --cov=ninja_schema --cov-report=xml tests
      - name: Coverage
        uses: codecov/codecov-action@v5
